server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848

    gateway:
      routes:
        - id: service-production
          uri: lb://service-production
          predicates:
            - Path=/api/v1/production/**

        - id: service-equipment
          uri: lb://service-equipment
          predicates:
            - Path=/api/v1/equipment/**

        - id: service-process
          uri: lb://service-process
          predicates:
            - Path=/api/v1/process/**

        - id: service-auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        # 添加直接路由支持
        - id: equipment-health
          uri: http://localhost:8082
          predicates:
            - Path=/api/health
          filters:
            - RewritePath=/api/health, /api/health

        - id: equipment-direct
          uri: http://localhost:8082
          predicates:
            - Path=/api/equipment/**

        - id: process-direct
          uri: http://localhost:8083
          predicates:
            - Path=/api/process/**

        - id: production-direct
          uri: http://localhost:8084
          predicates:
            - Path=/api/production/**

        # 图案管理路由
        - id: patterns
          uri: http://localhost:8083
          predicates:
            - Path=/api/patterns/**

        # 静态资源路由
        - id: uploads
          uri: http://localhost:8083
          predicates:
            - Path=/api/uploads/**

      globalcors:
        cors-configurations:
          '[/**]': # 对所有路径生效
            allowedOrigins: 
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://192.168.219.130:5173"
              - "http://192.168.219.130:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

