spring:
  cloud:
    gateway:
      routes:
        - id: service-production
          uri: lb://service-production
          predicates:
            - Path=/api/v1/production/**
          filters:
            - StripPrefix=2

        - id: service-equipment
          uri: lb://service-equipment
          predicates:
            - Path=/api/v1/equipment/**
          filters:
            - StripPrefix=2

        - id: service-process
          uri: lb://service-process
          predicates:
            - Path=/api/v1/process/**
          filters:
            - StripPrefix=2