spring:
  application:
    name: service-process
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    loadbalancer:
      enabled: true # ????????
      health-check:
        enabled: true # ??????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/process_service_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
server:
  port: 7000
  error:
    include-binding-errors: always
    include-message: always
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??
    map-underscore-to-camel-case: true # ??????
  mapper-locations: classpath*:/com.shoujike.process.mapper/**/*.xml # XML??????
  type-aliases-package: com.shoujike.product.entity # ??????
file:
  upload:
    dir: ./services/service-process/src/main/resources/static/uploads/patterns/