spring:
  application:
    name: service-production
  cloud:
    nacos:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      enabled: true # ????????
      health-check:
        enabled: true # ??????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MES?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
server:
  port: 8104
  error:
    include-binding-errors: always
    include-message: always
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??
    map-underscore-to-camel-case: true # ??????
  mapper-locations: classpath*:/com.shoujike.process.mapper/**/*.xml # XML??????
  type-aliases-package: com.shoujike.product.entity # ??????
